function A = mdl_rotKarman_zyx_b2i(phi, theta, psi)
 A = [1  sin(phi)*tan(theta)  cos(phi)*tan(theta); ...
      0  cos(phi)            -sin(phi); ...
      0  sin(phi)/cos(theta)  cos(phi)/cos(theta)];
end
