function A = mdl_rotEuler_zyx_b2i(phi, theta, psi)
 A = [cos(theta)*cos(psi) sin(theta)*sin(phi)*cos(psi)-cos(phi)*sin(psi) sin(theta)*cos(phi)*cos(psi)+sin(phi)*sin(psi); ...
      cos(theta)*sin(psi) sin(theta)*sin(phi)*sin(psi)+cos(phi)*cos(psi) sin(theta)*cos(phi)*sin(psi)-sin(phi)*cos(psi); ...
      -sin(theta)         cos(theta)*sin(phi)                            cos(theta)*cos(phi)];
end
