function Par = mdl_actuator_dynamics_par( ) 
% function Par = mdl_actuator_dynamics_par( ) 
%
%   Author1     : 
%
%   Date        : Winter 2018
%
%   Description : Submodel for esc-bldc dynamics
%
%   Parameters  : 
% 
%   Return      : Par -> Struct containing dynamic model parameters
%
%   This function was autogenerated by 04_identification/...
%   ...actuator_esc-bldc/ident_acutator_thrust.m 
%
%-------------------------------------------------------------------------%

Par.linearModelCoefs = [1; -0.68932];
Par.sampleTime = 0.1;