function F = mdl_actuator_staticMap( pwm ) 
% function F = mdl_actuator_staticMap( pwm ) 
%
%   Author1     : 
%
%   Date        : Winter 2018
%
%   Description : Submodel for esc-bldc dynamics
%
%   Parameters  : pwm -> Pulse width modulation [-]
% 
%   Return      : F -> Motor thrust [N] 
%
%   This function was autogenerated by 04_identification/...
%   ...actuator_esc-bldc/ident_acutator_thrust.m 
%
%-------------------------------------------------------------------------%

g = 9.81; % Gravity [m/s^2]
F = g*(-0.47932.*pwm.^3 + 0.96099.*pwm.^2 + 0.056959.*pwm + -0.0023029);