function pwm = mdl_actuator_staticMapInverse( F ) 
% function pwm = mdl_actuator_staticMapInverse( F ) 
%
%   Author1     : 
%
%   Date        : Winter 2018
%
%   Description : Submodel for esc-bldc dynamics
%
%   Parameters  : F -> Motor thrust [N]
% 
%   Return      : pwm -> Pulse width modulation [-]
%
%   This function was autogenerated by 04_identification/...
%   ...actuator_esc-bldc/ident_acutator_thrust.m 
%
%-------------------------------------------------------------------------%

Ftilde = F/9.81; % Thrust in kg [kg]
pwm =  -1709.6091 + 2249.777*cos(Ftilde*0.49905) + 388.2944*sin(Ftilde*0.49905) + -540.1101*cos(2*Ftilde*0.49905) + -190.5554*sin(2*Ftilde*0.49905);